### ISSUE TITLE
Botのチャンネル参加の際のチャンネルドロップダウンでチャンネルを選択したあと表示されない

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traQ-bot-console#325]
表示されないだけで追加はできる

**Comment by motoki317** [comment]
選択が表示されないのは `hide-selection` をつけてるからだけど、filter の文字列と重なって微妙になるから意図的につけたとか？
（外しても良いと思う）
<img width="522" alt="スクリーンショット 2022-02-14 13 43 34" src="https://user-images.githubusercontent.com/18257693/153801348-c701b2cf-7e4b-489d-a1b5-7bf5362e317a.png">

https://github.com/traPtitech/traQ-bot-console/blob/c4e460e72c6786bc94bec6b53bb919e7be04531c/src/views/BotDetail.vue#L120
